#spring.application.name=products-service
#server.port=8082
##
### MongoDB connection settings
###spring.data.mongodb.host=mongo
###spring.data.mongodb.port=27017
###spring.data.mongodb.database=products-service-db
#
#spring.data.mongodb.connection-timeout=3000000
#
#
#spring.data.mongodb.uri=mongodb://mongo:27017/products-service-db
#
#eureka.instance.hostname=localhost
#eureka.instance.prefer-ip-address=true
#eureka.instance.ip-address=192.168.1.37  # Replace with your desired IP address
#eureka.instance.instance-id=${spring.application.name}:${server.port}
#eureka.instance.non-secure-port=${server.port}
#eureka.instance.appname=products-service
#
#
### Eureka Client Configuration
#eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka
#eureka.client.fetchRegistry=true
#eureka.client.registerWithEureka=true
#
#logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
#logging.level.org.springframework.data.mongodb.core.MongoTemplate.Mongo=DEBUG
#logging.level.com.example.products_service.repository.ProductRepository=DEBUG
#
#
#
#




server:
  port: 8082

spring:
  application:
    name: products-service

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    prefer-ip-address: true



  data:
    mongodb:
      host: mongo
      port: 27015
      database: products-service-db

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate.Mongo: DEBUG
    com.example.products_service.repository.ProductRepository: DEBUG